draw_set_halign(fa_center)
draw_set_color(c_white)
draw_set_font(global.bigfont)
if (state == (145 << 0))
    draw_text((random_range(1, -1) + 480), (random_range(1, -1) + 500), ("ROUND " + string((wave + 1))))
