ratgrabbed = 0
grabbed = 0
state = (0 << 0)
hsp = 0
vsp = 0
grav = 0.5
flash = 1
unpickable = 0
hp = 0
grounded = 1
state = 0
playerid = 324
image_speed = 0
image_index = random_range(0, (image_number - 1))
mask_index = spr_player_mask
depth = -5
platformid = -4
hsp_carry = 0
vsp_carry = 0
thrown = 0
use_collision = 1
